apiVersion: v1
kind: Service
metadata:
  name: mdb-api
  labels:
    app: mdb-api
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8002
    targetPort: 8002
    nodePort: 30002
  selector:
    app: mdb-api